const pokemonData = [
    { dex: '1', gen: 1, name: 'bulbasaur', type: 'grass/poison', image: './media/images/1.png', audio: './media/audio/1.mp3' },
    { dex: '2', gen: 1, name: 'ivysaur', type: 'grass/poison', image: './media/images/2.png', audio: './media/audio/2.mp3' },
    { dex: '3', gen: 1, name: 'venusaur', type: 'grass/poison', image: './media/images/3.png', audio: './media/audio/3.mp3' },
    { dex: '4', gen: 1, name: 'charmander', type: 'fire', image: './media/images/4.png', audio: './media/audio/4.mp3' },
    { dex: '5', gen: 1, name: 'charmeleon', type: 'fire', image: './media/images/5.png', audio: './media/audio/5.mp3' },
    { dex: '6', gen: 1, name: 'charizard', type: 'fire/flying', image: './media/images/6.png', audio: './media/audio/6.mp3' },
    { dex: '7', gen: 1, name: 'squirtle', type: 'water', image: './media/images/7.png', audio: './media/audio/7.mp3' },
    { dex: '8', gen: 1, name: 'wartortle', type: 'water', image: './media/images/8.png', audio: './media/audio/8.mp3' },
    { dex: '9', gen: 1, name: 'blastoise', type: 'water', image: './media/images/9.png', audio: './media/audio/9.mp3' },
    { dex: '10', gen: 1, name: 'caterpie', type: 'bug', image: './media/images/10.png', audio: './media/audio/10.mp3' },
    { dex: '11', gen: 1, name: 'metapod', type: 'bug', image: './media/images/11.png', audio: './media/audio/11.mp3' },
    { dex: '12', gen: 1, name: 'butterfree', type: 'bug/flying', image: './media/images/12.png', audio: './media/audio/12.mp3' },
    { dex: '13', gen: 1, name: 'weedle', type: 'bug/poison', image: './media/images/13.png', audio: './media/audio/13.mp3' },
    { dex: '14', gen: 1, name: 'kakuna', type: 'bug/poison', image: './media/images/14.png', audio: './media/audio/14.mp3' },
    { dex: '15', gen: 1, name: 'beedrill', type: 'bug/poison', image: './media/images/15.png', audio: './media/audio/15.mp3' },
    { dex: '16', gen: 1, name: 'pidgey', type: 'normal/flying', image: './media/images/16.png', audio: './media/audio/16.mp3' },
    { dex: '17', gen: 1, name: 'pidgeotto', type: 'normal/flying', image: './media/images/17.png', audio: './media/audio/17.mp3' },
    { dex: '18', gen: 1, name: 'pidgeot', type: 'normal/flying', image: './media/images/18.png', audio: './media/audio/18.mp3' },
    { dex: '19', gen: 1, name: 'rattata', type: 'normal', image: './media/images/19.png', audio: './media/audio/19.mp3' },
    { dex: '20', gen: 1, name: 'raticate', type: 'normal', image: './media/images/20.png', audio: './media/audio/20.mp3' },
    { dex: '21', gen: 1, name: 'spearow', type: 'normal/flying', image: './media/images/21.png', audio: './media/audio/21.mp3' },
    { dex: '22', gen: 1, name: 'fearow', type: 'normal/flying', image: './media/images/22.png', audio: './media/audio/22.mp3' },
    { dex: '23', gen: 1, name: 'ekans', type: 'poison', image: './media/images/23.png', audio: './media/audio/23.mp3' },
    { dex: '24', gen: 1, name: 'arbok', type: 'poison', image: './media/images/24.png', audio: './media/audio/24.mp3' },
    { dex: '25', gen: 1, name: 'pikachu', type: 'electric', image: './media/images/25.png', audio: './media/audio/25.mp3' },
    { dex: '26', gen: 1, name: 'raichu', type: 'electric', image: './media/images/26.png', audio: './media/audio/26.mp3' },
    { dex: '27', gen: 1, name: 'sandshrew', type: 'ground', image: './media/images/27.png', audio: './media/audio/27.mp3' },
    { dex: '28', gen: 1, name: 'sandslash', type: 'ground', image: './media/images/28.png', audio: './media/audio/28.mp3' },
    { dex: '29', gen: 1, name: 'nidoran♀', type: 'poison', image: './media/images/29.png', audio: './media/audio/29.mp3' },
    { dex: '30', gen: 1, name: 'nidorina', type: 'poison', image: './media/images/30.png', audio: './media/audio/30.mp3' },
    { dex: '31', gen: 1, name: 'nidoqueen', type: 'poison/ground', image: './media/images/31.png', audio: './media/audio/31.mp3' },
    { dex: '32', gen: 1, name: 'nidoran♂', type: 'poison', image: './media/images/32.png', audio: './media/audio/32.mp3' },
    { dex: '33', gen: 1, name: 'nidorino', type: 'poison', image: './media/images/33.png', audio: './media/audio/33.mp3' },
    { dex: '34', gen: 1, name: 'nidoking', type: 'poison/ground', image: './media/images/34.png', audio: './media/audio/34.mp3' },
    { dex: '35', gen: 1, name: 'clefairy', type: 'fairy', image: './media/images/35.png', audio: './media/audio/35.mp3' },
    { dex: '36', gen: 1, name: 'clefable', type: 'fairy', image: './media/images/36.png', audio: './media/audio/36.mp3' },
    { dex: '37', gen: 1, name: 'vulpix', type: 'fire', image: './media/images/37.png', audio: './media/audio/37.mp3' },
    { dex: '38', gen: 1, name: 'ninetales', type: 'fire', image: './media/images/38.png', audio: './media/audio/38.mp3' },
    { dex: '39', gen: 1, name: 'jigglypuff', type: 'normal/fairy', image: './media/images/39.png', audio: './media/audio/39.mp3' },
    { dex: '40', gen: 1, name: 'wigglytuff', type: 'normal/fairy', image: './media/images/40.png', audio: './media/audio/40.mp3' },
    { dex: '41', gen: 1, name: 'zubat', type: 'poison/flying', image: './media/images/41.png', audio: './media/audio/41.mp3' },
    { dex: '42', gen: 1, name: 'golbat', type: 'poison/flying', image: './media/images/42.png', audio: './media/audio/42.mp3' },
    { dex: '43', gen: 1, name: 'oddish', type: 'grass/poison', image: './media/images/43.png', audio: './media/audio/43.mp3' },
    { dex: '44', gen: 1, name: 'gloom', type: 'grass/poison', image: './media/images/44.png', audio: './media/audio/44.mp3' },
    { dex: '45', gen: 1, name: 'vileplume', type: 'grass/poison', image: './media/images/45.png', audio: './media/audio/45.mp3' },
    { dex: '46', gen: 1, name: 'paras', type: 'bug/grass', image: './media/images/46.png', audio: './media/audio/46.mp3' },
    { dex: '47', gen: 1, name: 'parasect', type: 'bug/grass', image: './media/images/47.png', audio: './media/audio/47.mp3' },
    { dex: '48', gen: 1, name: 'venonat', type: 'bug/poison', image: './media/images/48.png', audio: './media/audio/48.mp3' },
    { dex: '49', gen: 1, name: 'venomoth', type: 'bug/poison', image: './media/images/49.png', audio: './media/audio/49.mp3' },
    { dex: '50', gen: 1, name: 'diglett', type: 'ground', image: './media/images/50.png', audio: './media/audio/50.mp3' },
    { dex: '51', gen: 1, name: 'dugtrio', type: 'ground', image: './media/images/51.png', audio: './media/audio/51.mp3' },
    { dex: '52', gen: 1, name: 'meowth', type: 'normal', image: './media/images/52.png', audio: './media/audio/52.mp3' },
    { dex: '53', gen: 1, name: 'persian', type: 'normal', image: './media/images/53.png', audio: './media/audio/53.mp3' },
    { dex: '54', gen: 1, name: 'psyduck', type: 'water', image: './media/images/54.png', audio: './media/audio/54.mp3' },
    { dex: '55', gen: 1, name: 'golduck', type: 'water', image: './media/images/55.png', audio: './media/audio/55.mp3' },
    { dex: '56', gen: 1, name: 'mankey', type: 'fighting', image: './media/images/56.png', audio: './media/audio/56.mp3' },
    { dex: '57', gen: 1, name: 'primeape', type: 'fighting', image: './media/images/57.png', audio: './media/audio/57.mp3' },
    { dex: '58', gen: 1, name: 'growlithe', type: 'fire', image: './media/images/58.png', audio: './media/audio/58.mp3' },
    { dex: '59', gen: 1, name: 'arcanine', type: 'fire', image: './media/images/59.png', audio: './media/audio/59.mp3' },
    { dex: '60', gen: 1, name: 'poliwag', type: 'water', image: './media/images/60.png', audio: './media/audio/60.mp3' },
    { dex: '61', gen: 1, name: 'poliwhirl', type: 'water', image: './media/images/61.png', audio: './media/audio/61.mp3' },
    { dex: '62', gen: 1, name: 'poliwrath', type: 'water/fighting', image: './media/images/62.png', audio: './media/audio/62.mp3' },
    { dex: '63', gen: 1, name: 'abra', type: 'psychic', image: './media/images/63.png', audio: './media/audio/63.mp3' },
    { dex: '64', gen: 1, name: 'kadabra', type: 'psychic', image: './media/images/64.png', audio: './media/audio/64.mp3' },
    { dex: '65', gen: 1, name: 'alakazam', type: 'psychic', image: './media/images/65.png', audio: './media/audio/65.mp3' },
    { dex: '66', gen: 1, name: 'machop', type: 'fighting', image: './media/images/66.png', audio: './media/audio/66.mp3' },
    { dex: '67', gen: 1, name: 'machoke', type: 'fighting', image: './media/images/67.png', audio: './media/audio/67.mp3' },
    { dex: '68', gen: 1, name: 'machamp', type: 'fighting', image: './media/images/68.png', audio: './media/audio/68.mp3' },
    { dex: '69', gen: 1, name: 'bellsprout', type: 'grass/poison', image: './media/images/69.png', audio: './media/audio/69.mp3' },
    { dex: '70', gen: 1, name: 'weepinbell', type: 'grass/poison', image: './media/images/70.png', audio: './media/audio/70.mp3' },
    { dex: '71', gen: 1, name: 'victreebel', type: 'grass/poison', image: './media/images/71.png', audio: './media/audio/71.mp3' },
    { dex: '72', gen: 1, name: 'tentacool', type: 'water/poison', image: './media/images/72.png', audio: './media/audio/72.mp3' },
    { dex: '73', gen: 1, name: 'tentacruel', type: 'water/poison', image: './media/images/73.png', audio: './media/audio/73.mp3' },
    { dex: '74', gen: 1, name: 'geodude', type: 'rock/ground', image: './media/images/74.png', audio: './media/audio/74.mp3' },
    { dex: '75', gen: 1, name: 'graveler', type: 'rock/ground', image: './media/images/75.png', audio: './media/audio/75.mp3' },
    { dex: '76', gen: 1, name: 'golem', type: 'rock/ground', image: './media/images/76.png', audio: './media/audio/76.mp3' },
    { dex: '77', gen: 1, name: 'ponyta', type: 'fire', image: './media/images/77.png', audio: './media/audio/77.mp3' },
    { dex: '78', gen: 1, name: 'rapidash', type: 'fire', image: './media/images/78.png', audio: './media/audio/78.mp3' },
    { dex: '79', gen: 1, name: 'slowpoke', type: 'water/psychic', image: './media/images/79.png', audio: './media/audio/79.mp3' },
    { dex: '80', gen: 1, name: 'slowbro', type: 'water/psychic', image: './media/images/80.png', audio: './media/audio/80.mp3' },
    { dex: '81', gen: 1, name: 'magnemite', type: 'electric/steel', image: './media/images/81.png', audio: './media/audio/81.mp3' },
    { dex: '82', gen: 1, name: 'magneton', type: 'electric/steel', image: './media/images/82.png', audio: './media/audio/82.mp3' },
    { dex: '83', gen: 1, name: 'farfetch\'d', type: 'normal/flying', image: './media/images/83.png', audio: './media/audio/83.mp3' },
    { dex: '84', gen: 1, name: 'doduo', type: 'normal/flying', image: './media/images/84.png', audio: './media/audio/84.mp3' },
    { dex: '85', gen: 1, name: 'dodrio', type: 'normal/flying', image: './media/images/85.png', audio: './media/audio/85.mp3' },
    { dex: '86', gen: 1, name: 'seel', type: 'water', image: './media/images/86.png', audio: './media/audio/86.mp3' },
    { dex: '87', gen: 1, name: 'dewgong', type: 'water/ice', image: './media/images/87.png', audio: './media/audio/87.mp3' },
    { dex: '88', gen: 1, name: 'grimer', type: 'poison', image: './media/images/88.png', audio: './media/audio/88.mp3' },
    { dex: '89', gen: 1, name: 'muk', type: 'poison', image: './media/images/89.png', audio: './media/audio/89.mp3' },
    { dex: '90', gen: 1, name: 'shellder', type: 'water', image: './media/images/90.png', audio: './media/audio/90.mp3' },
    { dex: '91', gen: 1, name: 'cloyster', type: 'water/ice', image: './media/images/91.png', audio: './media/audio/91.mp3' },
    { dex: '92', gen: 1, name: 'gastly', type: 'ghost/poison', image: './media/images/92.png', audio: './media/audio/92.mp3' },
    { dex: '93', gen: 1, name: 'haunter', type: 'ghost/poison', image: './media/images/93.png', audio: './media/audio/93.mp3' },
    { dex: '94', gen: 1, name: 'gengar', type: 'ghost/poison', image: './media/images/94.png', audio: './media/audio/94.mp3' },
    { dex: '95', gen: 1, name: 'onix', type: 'rock/ground', image: './media/images/95.png', audio: './media/audio/95.mp3' },
    { dex: '96', gen: 1, name: 'drowzee', type: 'psychic', image: './media/images/96.png', audio: './media/audio/96.mp3' },
    { dex: '97', gen: 1, name: 'hypno', type: 'psychic', image: './media/images/97.png', audio: './media/audio/97.mp3' },
    { dex: '98', gen: 1, name: 'krabby', type: 'water', image: './media/images/98.png', audio: './media/audio/98.mp3' },
    { dex: '99', gen: 1, name: 'kingler', type: 'water', image: './media/images/99.png', audio: './media/audio/99.mp3' },
    { dex: '100', gen: 1, name: 'voltorb', type: 'electric', image: './media/images/100.png', audio: './media/audio/100.mp3' },
    { dex: '101', gen: 1, name: 'electrode', type: 'electric', image: './media/images/101.png', audio: './media/audio/101.mp3' },
    { dex: '102', gen: 1, name: 'exeggcute', type: 'grass/psychic', image: './media/images/102.png', audio: './media/audio/102.mp3' },
    { dex: '103', gen: 1, name: 'exeggutor', type: 'grass/psychic', image: './media/images/103.png', audio: './media/audio/103.mp3' },
    { dex: '104', gen: 1, name: 'cubone', type: 'ground', image: './media/images/104.png', audio: './media/audio/104.mp3' },
    { dex: '105', gen: 1, name: 'marowak', type: 'ground', image: './media/images/105.png', audio: './media/audio/105.mp3' },
    { dex: '106', gen: 1, name: 'hitmonlee', type: 'fighting', image: './media/images/106.png', audio: './media/audio/106.mp3' },
    { dex: '107', gen: 1, name: 'hitmonchan', type: 'fighting', image: './media/images/107.png', audio: './media/audio/107.mp3' },
    { dex: '108', gen: 1, name: 'lickitung', type: 'normal', image: './media/images/108.png', audio: './media/audio/108.mp3' },
    { dex: '109', gen: 1, name: 'koffing', type: 'poison', image: './media/images/109.png', audio: './media/audio/109.mp3' },
    { dex: '110', gen: 1, name: 'weezing', type: 'poison', image: './media/images/110.png', audio: './media/audio/110.mp3' },
    { dex: '111', gen: 1, name: 'rhyhorn', type: 'ground/rock', image: './media/images/111.png', audio: './media/audio/111.mp3' },
    { dex: '112', gen: 1, name: 'rhydon', type: 'ground/rock', image: './media/images/112.png', audio: './media/audio/112.mp3' },
    { dex: '113', gen: 1, name: 'chansey', type: 'normal', image: './media/images/113.png', audio: './media/audio/113.mp3' },
    { dex: '114', gen: 1, name: 'tangela', type: 'grass', image: './media/images/114.png', audio: './media/audio/114.mp3' },
    { dex: '115', gen: 1, name: 'kangaskhan', type: 'normal', image: './media/images/115.png', audio: './media/audio/115.mp3' },
    { dex: '116', gen: 1, name: 'horsea', type: 'water', image: './media/images/116.png', audio: './media/audio/116.mp3' },
    { dex: '117', gen: 1, name: 'seadra', type: 'water', image: './media/images/117.png', audio: './media/audio/117.mp3' },
    { dex: '118', gen: 1, name: 'goldeen', type: 'water', image: './media/images/118.png', audio: './media/audio/118.mp3' },
    { dex: '119', gen: 1, name: 'seaking', type: 'water', image: './media/images/119.png', audio: './media/audio/119.mp3' },
    { dex: '120', gen: 1, name: 'staryu', type: 'water', image: './media/images/120.png', audio: './media/audio/120.mp3' },
    { dex: '121', gen: 1, name: 'starmie', type: 'water/psychic', image: './media/images/121.png', audio: './media/audio/121.mp3' },
    { dex: '122', gen: 1, name: 'mr. mime', type: 'psychic/fairy', image: './media/images/122.png', audio: './media/audio/122.mp3' },
    { dex: '123', gen: 1, name: 'scyther', type: 'bug/flying', image: './media/images/123.png', audio: './media/audio/123.mp3' },
    { dex: '124', gen: 1, name: 'jynx', type: 'ice/psychic', image: './media/images/124.png', audio: './media/audio/124.mp3' },
    { dex: '125', gen: 1, name: 'electabuzz', type: 'electric', image: './media/images/125.png', audio: './media/audio/125.mp3' },
    { dex: '126', gen: 1, name: 'magmar', type: 'fire', image: './media/images/126.png', audio: './media/audio/126.mp3' },
    { dex: '127', gen: 1, name: 'pinsir', type: 'bug', image: './media/images/127.png', audio: './media/audio/127.mp3' },
    { dex: '128', gen: 1, name: 'tauros', type: 'normal', image: './media/images/128.png', audio: './media/audio/128.mp3' },
    { dex: '129', gen: 1, name: 'magikarp', type: 'water', image: './media/images/129.png', audio: './media/audio/129.mp3' },
    { dex: '130', gen: 1, name: 'gyarados', type: 'water/flying', image: './media/images/130.png', audio: './media/audio/130.mp3' },
    { dex: '131', gen: 1, name: 'lapras', type: 'water/ice', image: './media/images/131.png', audio: './media/audio/131.mp3' },
    { dex: '132', gen: 1, name: 'ditto', type: 'normal', image: './media/images/132.png', audio: './media/audio/132.mp3' },
    { dex: '133', gen: 1, name: 'eevee', type: 'normal', image: './media/images/133.png', audio: './media/audio/133.mp3' },
    { dex: '134', gen: 1, name: 'vaporeon', type: 'water', image: './media/images/134.png', audio: './media/audio/134.mp3' },
    { dex: '135', gen: 1, name: 'jolteon', type: 'electric', image: './media/images/135.png', audio: './media/audio/135.mp3' },
    { dex: '136', gen: 1, name: 'flareon', type: 'fire', image: './media/images/136.png', audio: './media/audio/136.mp3' },
    { dex: '137', gen: 1, name: 'porygon', type: 'normal', image: './media/images/137.png', audio: './media/audio/137.mp3' },
    { dex: '138', gen: 1, name: 'omanyte', type: 'rock/water', image: './media/images/138.png', audio: './media/audio/138.mp3' },
    { dex: '139', gen: 1, name: 'omastar', type: 'rock/water', image: './media/images/139.png', audio: './media/audio/139.mp3' },
    { dex: '140', gen: 1, name: 'kabuto', type: 'rock/water', image: './media/images/140.png', audio: './media/audio/140.mp3' },
    { dex: '141', gen: 1, name: 'kabutops', type: 'rock/water', image: './media/images/141.png', audio: './media/audio/141.mp3' },
    { dex: '142', gen: 1, name: 'aerodactyl', type: 'rock/flying', image: './media/images/142.png', audio: './media/audio/142.mp3' },
    { dex: '143', gen: 1, name: 'snorlax', type: 'normal', image: './media/images/143.png', audio: './media/audio/143.mp3' },
    { dex: '144', gen: 1, name: 'articuno', type: 'ice/flying', image: './media/images/144.png', audio: './media/audio/144.mp3' },
    { dex: '145', gen: 1, name: 'zapdos', type: 'electric/flying', image: './media/images/145.png', audio: './media/audio/145.mp3' },
    { dex: '146', gen: 1, name: 'moltres', type: 'fire/flying', image: './media/images/146.png', audio: './media/audio/146.mp3' },
    { dex: '147', gen: 1, name: 'dratini', type: 'dragon', image: './media/images/147.png', audio: './media/audio/147.mp3' },
    { dex: '148', gen: 1, name: 'dragonair', type: 'dragon', image: './media/images/148.png', audio: './media/audio/148.mp3' },
    { dex: '149', gen: 1, name: 'dragonite', type: 'dragon/flying', image: './media/images/149.png', audio: './media/audio/149.mp3' },
    { dex: '150', gen: 1, name: 'mewtwo', type: 'psychic', image: './media/images/150.png', audio: './media/audio/150.mp3' },
    { dex: '151', gen: 1, name: 'mew', type: 'psychic', image: './media/images/151.png', audio: './media/audio/151.mp3' },












    { dex: '152', gen: 2, name: 'chikorita', type: 'grass', image: './media/images/152.png' },
    { dex: '155', gen: 2, name: 'cyndaquil', type: 'fire', image: './media/images/155.png' },
    { dex: '158', gen: 2, name: 'totodile', type: 'water', image: './media/images/158.png' },

    { dex: '252', gen: 3, name: 'treecko', type: 'grass', image: './media/images/252.png' },
    { dex: '255', gen: 3, name: 'torchic', type: 'fire', image: './media/images/255.png' },
    { dex: '258', gen: 3, name: 'mudkip', type: 'water', image: './media/images/258.png' },

    { dex: '387', gen: 4, name: 'turtwig', type: 'grass', image: './media/images/387.png' },
    { dex: '390', gen: 4, name: 'chimchar', type: 'fire', image: './media/images/390.png' },
    { dex: '393', gen: 4, name: 'piplup', type: 'water', image: './media/images/393.png' },

    { dex: '495', gen: 5, name: 'snivy', type: 'grass', image: './media/images/495.png' },
    { dex: '498', gen: 5, name: 'tepig', type: 'fire', image: './media/images/498.png' },
    { dex: '501', gen: 5, name: 'oshawott', type: 'water', image: './media/images/501.png' },

    { dex: '650', gen: 6, name: 'chespin', type: 'grass', image: './media/images/650.png' },
    { dex: '653', gen: 6, name: 'fennekin', type: 'fire', image: './media/images/653.png' },
    { dex: '656', gen: 6, name: 'froakie', type: 'water', image: './media/images/656.png' },

    { dex: '722', gen: 7, name: 'rowlet', type: 'grass/flying', image: './media/images/722.png' },
    { dex: '725', gen: 7, name: 'litten', type: 'fire', image: './media/images/725.png' },
    { dex: '728', gen: 7, name: 'popplio', type: 'water', image: './media/images/728.png' },

    { dex: '810', gen: 8, name: 'grookey', type: 'grass', image: './media/images/810.png' },
    { dex: '813', gen: 8, name: 'scorbunny', type: 'fire', image: './media/images/813.png' },
    { dex: '816', gen: 8, name: 'sobble', type: 'water', image: './media/images/816.png' },
    
    { dex: '906', gen: 9, name: 'sprigatito', type: 'grass', image: './media/images/906.png' },
    { dex: '909', gen: 9, name: 'fuecoco', type: 'fire', image: './media/images/909.png' },
    { dex: '912', gen: 9, name: 'quaxly', type: 'water', image: './media/images/912.png' }
];
